export class Proyecto {
    constructor(
        public proyecto: string,
        public descripcion: string,
        public objetivo: string,
        public idOrganizacion: string,
        public organizacion: number,
        public idArea: number,
        public area: number,
        public idRango: string,
        public rango: string,
        public idPoblacion: string,
        public poblacion: string,
        public beneficioInstitucional: string,
        public comentarios: string,
        public recursosEconomicos: string,
        public horasProyecto: string,
        public descripcionFormacion: string,
        public constanciaParticipacion: string,
        public descripcionBeneficiosAlumno: boolean,
        public indicadoresImpactoSocial: number,
        public noVacantes: number,
        public listaApoyos: [{ idProyecto:number, idApoyo:number, apoyo:string, id:number, fechaCreacion: string, activo:boolean }],
        public listaLineasTrabajo: [{ idProyecto:number, idLineaTrabajo:number, lineaTrabajo:string, id:number, fechaCreacion: string, activo:boolean }],
        public fechaInicio: string,
        public fechaTermino: string,
        public idPeriodo: number,
        public periodo: string,
        public disponible: boolean,
        public idUniversidad: number,
        public universidad: string,
        public idEstadoProyecto: number,
        public estadoProyecto: string,
        public observaciones: string,
        public activo: boolean,
        public id?: number,
        
    ) { }

}